spring:
  application:
    name: secret_stash
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  data:
    redis:
      repositories:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/${keycloak.realm}
          jwk-set-uri: http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/certs
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceName: secret-stash-scheduler
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.clusterCheckinInterval: 20000
      org.quartz.threadPool.threadCount: 5

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /docs/swagger-ui.html
  api-docs:
    path: /docs/v3/api-docs
  default-produces-media-type: application/json

keycloak:
  auth-server-url: http://localhost:8080
  realm: bitnet

rate:
  limit:
    default-limit: 10
    window-seconds: 1
