spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/${keycloak.realm}
          jwk-set-uri: http://keycloak:8080/realms/${keycloak.realm}/protocol/openid-connect/certs
server:
  error:
    include-stacktrace: never
