spring:
  application:
    name: secret_stash
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bitnet
          jwk-set-uri: http://localhost:8080/realms/bitnet/protocol/openid-connect/certs

server:
  port: 8081
